#ifndef RUNNER_NATIVE_SESSION_SESSION_TYPES_H_
#define RUNNER_NATIVE_SESSION_SESSION_TYPES_H_

#include <cstdint>
#include <string>

#include "native/video/video_types.h"

namespace pctv {

struct NativeSnapshot {
  std::string state;
  std::string user_message;
  bool capture_ready = false;
  bool encoder_ready = false;
  bool signaling_ready = false;
  bool native_video_path_ready = false;
  std::string error_code;
  std::string developer_message;
  double target_fps = 30.0;
  double capture_callback_fps = 0.0;
  double captured_fps = 0.0;
  double target_admission_fps = 0.0;
  double admitted_frame_fps = 0.0;
  double converted_fps = 0.0;
  double encoder_accepted_fps = 0.0;
  double encoder_input_fps = 0.0;
  double encoded_fps = 0.0;
  double sent_video_fps = 0.0;
  double sent_access_unit_fps = 0.0;
  double cadence_dropped_fps = 0.0;
  double encoder_busy_dropped_fps = 0.0;
  double conversion_busy_dropped_fps = 0.0;
  double capture_frame_interval_average_ms = 0.0;
  double capture_frame_interval_p95_ms = 0.0;
  double encode_frame_interval_average_ms = 0.0;
  double send_frame_interval_average_ms = 0.0;
  double send_frame_interval_p95_ms = 0.0;
  double capture_to_convert_average_ms = 0.0;
  double convert_to_encode_average_ms = 0.0;
  double encode_duration_average_ms = 0.0;
  double encode_duration_p95_ms = 0.0;
  double encode_to_send_average_ms = 0.0;
  double video_queue_wait_average_ms = 0.0;
  double video_queue_wait_p95_ms = 0.0;
  std::uint64_t captured_frames = 0;
  std::uint64_t capture_replaced_frames = 0;
  std::uint64_t cadence_skipped_frames = 0;
  std::uint64_t conversion_backpressure_dropped_frames = 0;
  std::uint64_t encoder_backpressure_dropped_frames = 0;
  std::uint64_t transport_backpressure_dropped_frames = 0;
  std::uint64_t stale_video_dropped_frames = 0;
  std::uint64_t shutdown_dropped_frames = 0;
  std::uint64_t total_dropped_frames = 0;
  std::uint64_t capture_dropped_frames = 0;
  std::uint64_t conversion_dropped_frames = 0;
  std::uint64_t encoder_input_dropped_frames = 0;
  std::uint64_t encoded_frames = 0;
  std::uint64_t transport_dropped_frames = 0;
  std::uint64_t duplicated_frames = 0;
  std::uint64_t last_processed_frame_sequence = 0;
  std::uint64_t codec_config_sent = 0;
  std::uint64_t key_frames_sent = 0;
  std::uint64_t packets_sent = 0;
  std::uint64_t bytes_sent = 0;
  std::uint64_t send_completed_bytes = 0;
  double socket_send_calls_per_second = 0.0;
  double average_packet_send_duration_ms = 0.0;
  double access_unit_send_duration_average_ms = 0.0;
  double access_unit_send_duration_p95_ms = 0.0;
  std::uint64_t pending_send_bytes = 0;
  std::string last_socket_error;
  int queue_depth_capture = 0;
  int queue_depth_encoder = 0;
  int queue_depth_transport = 0;
  double last_capture_to_encode_ms = 0.0;
  double average_capture_to_encode_ms = 0.0;
  double max_capture_to_encode_ms = 0.0;
  double admitted_to_encoded_ratio = 0.0;
  std::string selected_profile = "lowLatency720p30";
  std::string output_resolution = "1280x720";
  int current_bitrate_kbps = 6000;
  double target_frame_interval_ms = 33.333;
  double stale_video_dropped_fps = 0.0;
  std::string selected_encoder_name = "unknown";
  bool selected_encoder_hardware = false;
  bool selected_encoder_async = false;
  bool encoder_d3d11_aware = false;
  std::string encoder_input_format;
  std::string encoder_output_format;
  double average_encode_duration_ms = 0.0;
  std::uint64_t encoder_backpressure_count = 0;
  std::uint64_t encoder_not_accepting_count = 0;
  std::uint64_t process_input_calls = 0;
  std::uint64_t process_input_accepted = 0;
  std::uint64_t process_input_not_accepting = 0;
  std::uint64_t process_input_retries = 0;
  std::uint64_t process_output_calls = 0;
  std::uint64_t process_output_frames = 0;
  double process_input_duration_average_ms = 0.0;
  double process_input_duration_p95_ms = 0.0;
  double process_output_duration_average_ms = 0.0;
  double process_output_duration_p95_ms = 0.0;
  std::string bgra_to_nv12_mode = "cpuBgraToNv12";
  bool gpu_readback_per_frame = true;
  bool texture_reuse_enabled = true;
  std::string low_latency_options_applied;
  std::string unsupported_encoder_options;
  std::string bottleneck_summary = "unknown";
  std::string last_encode_error;
  std::string last_send_error;
  bool audio_enabled = false;
  std::string audio_capture_state = "disabled";
  std::string audio_device_name;
  int audio_input_sample_rate = 0;
  int audio_input_channels = 0;
  int audio_encoded_sample_rate = 48000;
  int audio_encoded_channels = 2;
  std::uint64_t captured_audio_packets = 0;
  std::uint64_t encoded_audio_packets = 0;
  std::uint64_t sent_audio_packets = 0;
  double audio_capture_fps = 0.0;
  double audio_encode_average_ms = 0.0;
  int audio_queue_depth = 0;
  std::uint64_t audio_dropped_packets = 0;
  std::string audio_last_error;
  double video_fps_audio_disabled = 0.0;
  double video_fps_audio_enabled = 0.0;
  double audio_cpu_time_ms = 0.0;
  double packet_writer_video_wait_ms = 0.0;
  double packet_writer_audio_wait_ms = 0.0;
  std::string playback_state = "idle";
  std::uint64_t pause_requests_received = 0;
  std::uint64_t resume_requests_received = 0;
  std::uint64_t playback_command_acks_sent = 0;
  std::uint64_t playback_command_errors_sent = 0;
  std::uint64_t resume_codec_config_resends = 0;
  std::string local_speaker_mute_mode = "pcAndTv";
  std::string local_speaker_mute_state = "disabled";
  std::string local_speaker_mute_last_error;
  bool pc_local_audio_mute_requested = false;
  bool pc_local_audio_mute_supported = false;
  bool pc_local_audio_mute_applied = false;
  bool pc_local_audio_original_mute_state = false;
  bool tv_audio_streaming = false;
  bool audio_capture_active = false;
  bool audio_encoder_active = false;
  bool audio_transport_active = false;
  std::string audio_routing_mode = "defaultRenderEndpointLoopback";
  std::string audio_mute_unsupported_reason;
  std::string tv_audio_source_device_id;
  std::string tv_audio_source_device_name;
  std::string pc_monitor_device_id;
  std::string pc_monitor_device_name;
  bool local_monitor_active = false;
  bool local_monitor_muted = false;
  int local_monitor_queue_depth = 0;
  std::uint64_t local_monitor_dropped_buffers = 0;
  std::string audio_capture_format;
  std::string audio_monitor_format;
  std::string audio_routing_unsupported_reason;
  std::string requested_profile = "lowLatency720p30";
  std::string applied_profile = "lowLatency720p30";
  std::string profile_fallback_reason;
  int output_width = 1280;
  int output_height = 720;
  int target_bitrate_kbps = 6000;
  std::string encoder_name = "unknown";
  bool hardware_encoder_active = false;
  bool encoder_supports_requested_resolution = false;
  int receiver_max_width = 0;
  int receiver_max_height = 0;
  int source_display_width = 0;
  int source_display_height = 0;
  double source_display_refresh_hz = 0.0;
  std::string source_display_device_name;
  std::uint64_t capture_system_relative_time_ns = 0;
  std::uint64_t sender_generated_pts_us = 0;
  std::uint64_t source_timestamp_delta_us = 0;
  double capture_interval_from_source_p50_ms = 0.0;
  int receiver_max_fps = 0;
  double capture_interval_from_source_p95_ms = 0.0;
  double capture_interval_from_source_max_ms = 0.0;
  std::string video_pts_source = "unavailable";
  bool receiver_supports_4k30 = false;
  double capture_fps_recent = 0.0;
  double conversion_fps_recent = 0.0;
  double encoder_input_fps_recent = 0.0;
  double encoder_output_fps_recent = 0.0;
  double transport_video_fps_recent = 0.0;
  double receiver_presented_fps_recent = 0.0;
  double receiver_received_fps_recent = 0.0;
  double receiver_decoder_input_fps_recent = 0.0;
  double receiver_decoder_output_fps_recent = 0.0;
  std::uint64_t receiver_decoder_output_released = 0;
  std::uint64_t receiver_decoder_output_released_immediate = 0;
  std::uint64_t receiver_decoder_output_released_scheduled = 0;
  std::uint64_t receiver_on_frame_rendered_callbacks = 0;
  std::string receiver_video_render_mode = "unavailable";
  double receiver_pts_interval_p50_ms = 0.0;
  std::uint64_t receiver_pts_regression_count = 0;
  double conversion_duration_p95_ms = 0.0;
  double encoder_queue_wait_p95_ms = 0.0;
  double transport_send_p95_ms = 0.0;
};

struct StartSessionOptions {
  std::string receiver_host;
  int receiver_port = 50720;
  std::string request_json;
  std::string source_id;
  std::string tv_audio_source_device_id;
  std::string pc_monitor_device_id;
  bool audio_enabled = true;
  bool pc_local_audio_mute_requested = false;
  VideoStreamConfig video;
};

}  // namespace pctv

#endif  // RUNNER_NATIVE_SESSION_SESSION_TYPES_H_
